use_frameworks!

platform :ios, '8.0'

target 'WJLTestTrunk_Example' do
  pod 'WJLTestTrunk', :path => '../'

  target 'WJLTestTrunk_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
